[tool.pytest.ini_options]
testpaths = ["."]
python_files = ["test_*.py"]

[tool.coverage.run]
source = ["."]
omit = ["test_*.py"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if __name__ == .__main__.:",
]
